my_dbt_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_HOST') }}"
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASS') }}"
      port: "{{ env_var('DBT_PORT') | as_number }}"
      dbname: "{{ env_var('DBT_DB') }}"
      schema: "{{ env_var('DBT_SCHEMA') }}"