services:
  erp-db:
    image: postgres:16
    container_name: erp-db
    environment:
      POSTGRES_DB: erp
      POSTGRES_USER: erp_user
      POSTGRES_PASSWORD: erp_pass
    ports:
      - "5433:5432"   
    volumes:
      - erp_data:/var/lib/postgresql/data
      - ./erp/initdb:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U erp_user -d erp"]
      interval: 10s
      timeout: 5s
      retries: 10

  dw-db:
    image: postgres:16
    container_name: dw-db
    environment:
      POSTGRES_DB: dw
      POSTGRES_USER: dw_admin
      POSTGRES_PASSWORD: dw_admin_pass
    ports:
      - "5434:5432"
    volumes:
      - dw_data:/var/lib/postgresql/data
      - ./dw/initdb:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dw_admin -d dw"]
      interval: 10s
      timeout: 5s
      retries: 10

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:latest
    container_name: dbt
    working_dir: /usr/app
    volumes:
      - ./dbt:/usr/app                     
    environment:
      DBT_HOST: dw-db                        
      DBT_PORT: "5432"                       
      DBT_DB: dw
      DBT_USER: dw_admin                     
      DBT_PASS: dw_admin_pass
      DBT_SCHEMA: silver                     
      DBT_PROFILES_DIR: /usr/app             
    depends_on:
      - dw-db

  dagster-dev:
    image: python:3.11-slim
    container_name: dagster-dev
    working_dir: /opt/dagster/app
    volumes:
      - ./orchestration:/opt/dagster/app
      - ./dbt:/usr/app
    environment:
      AIRBYTE_HOST: host.docker.internal
      AIRBYTE_PORT: "8000"
      AIRBYTE_CONNECTION_ID: "51bcabfe-185a-455f-b882-c1a4f7021002"
      DBT_PROFILES_DIR: /usr/app
      DBT_PROJECT_DIR: /usr/app
      PYTHONUNBUFFERED: "1"
    ports:
      - "3000:3000"
    depends_on:
      dw-db:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"   # útil no Linux puro
    command:
      [
        "bash","-lc",
        "pip install --no-cache-dir \
          dagster==1.7.15 dagster-webserver==1.7.15 \
          dagster-airbyte==0.23.15 dagster-dbt==0.23.15 \
          dbt-postgres==1.9.0 \
        && dagster dev -m repo -h 0.0.0.0 -p 3000"
      ]

volumes:
  erp_data:
  dw_data:
